### ISSUE TITLE
Labels of degree?

### ISSUE THREAD

**Issue by vlasvlasvlas** [turban/Leaflet.Graticule#6]
Nice plugin!

is there a way to include the label of the degree by each line (only on boundaries of the map)

this kind of label
<img src="http://www.georeference.org/doc/images/sc_layout_graticule_labels.gif"></img>

**Comment by dracodoc** [comment]
Another option is to have a pop up when user clicked on line. I guess this is easier to implement than labels above.

**Comment by dracodoc** [comment]
I found [this plugin](https://github.com/cloudybay/leaflet.latlng-graticule) have labels.

**Comment by dswdejonge** [comment]
The tutorial for using [Leaflet in R ](http://rstudio.github.io/leaflet/morefeatures.html#graticule) refers to this package to add a graticule, by using the function `addGraticule`. There is, however, [another plugin](https://github.com/ablakey/Leaflet.SimpleGraticule) for Leaflet that can be used in R to add a graticules, by using the function `addSimpleGraticule`, which does allow labeling of the latitude and longitude lines in the margins.

**Comment by vlasvlasvlas** [comment]
Ok Thanks this is like 3 years old now, ill check updates.

Thanks!
